# Generated by Django 5.0.4 on 2024-05-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('telemovel', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('servico', models.TextField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agenda')),
            ],
        ),
    ]
