# Generated by Django 5.0.5 on 2024-05-23 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cliente_apelido_alter_agenda_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='modelo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telemovel',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro'),
        ),
    ]
