# Generated by Django 5.0.5 on 2024-05-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_carro_remove_cliente_ano_remove_cliente_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='telemovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
            preserve_default=False,
        ),
    ]
