# Generated by Django 5.0.4 on 2024-05-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_carro_telemovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='perm',
            field=models.CharField(default='cliente', max_length=50),
        ),
    ]
