# Generated by Django 5.0.4 on 2024-05-28 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cliente_perm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('telemovel', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('perm', models.CharField(default='mecanico', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='agenda',
            name='telemovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.mecanico'),
            preserve_default=False,
        ),
    ]
