# Generated by Django 5.0.4 on 2024-06-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mecanico_agenda_telemovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app.faturas')),
            ],
        ),
    ]
