# Generated by Django 5.0.6 on 2024-06-17 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_item_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicos',
        ),
    ]
